### ISSUE TITLE
State saving on deploy breaks certain workflows

### ISSUE THREAD

**Issue by Kwpolska** [getnikola/nikola#2242]
If you put `nikola deploy` in a `pre-push` git hook, it will edit the state file, thus leading to uncommitted changes. Forever, because it will change after every push.

**Comment by ralsina** [comment]
I don't see how this can be avoided, to be honest.

**Comment by tritium21** [comment]
Why not put the state in the cache folder - something that shouldn't be in the repository in the first place.  If the cache is wiped out, the state is likely to be worthless anyways.

**Comment by ralsina** [comment]
Because state is meant to be persistent. That's the whole point. The user
should be able to delete the contents of cache/ without causing anything
more than a longer build.

**Comment by tritium21** [comment]
The state file currently holds the datetime of the last deploy.  I don't see the value of keeping that information between cache wipes.  It's not even used everywhere it's supposed to be (see: #2317), and it's interfering with some workflows, as stated, and being unconfigurable, it is meaningless to anyone with multiple config files.

Moving it to the cache directory (a configurable location, and something you would have to change with multiple config files) solves that issue, this issue, and sacrifices almost nothing.

**Comment by tritium21** [comment]
Or, perhaps, make its location configurable so you can put it outside the repository.  Given what is in the file, I don't understand the value of keeping the state with the site source.

**Comment by Kwpolska** [comment]
And who even cares about the last deploy date?

**Comment by ralsina** [comment]
Fixed in https://github.com/getnikola/nikola/commit/e705bf9ec4fac4f20dbbb4ddb6570761d3d84b4c

**Comment by Kwpolska** [comment]
(For `nikola github_deploy` only; `nikola deploy` isn’t fixed but doesn’t necessarily *need* to be)

**Comment by ralsina** [comment]
Exactly. If someone complains again we will see.
